services:
  db:
    image: postgres:14.19-alpine3.21
    container_name: product_crud_db
    ports:
      - ${POSTGRES_EXPOSE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db:/var/lib/postgresql/data
